// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfHtlzku7iAO27qoUq-tkLmBjAsQYg7M',
    appId: '1:538710833734:web:2805917dca32c76a976847',
    messagingSenderId: '538710833734',
    projectId: 'iot-project-b170f',
    authDomain: 'iot-project-b170f.firebaseapp.com',
    databaseURL: 'https://iot-project-b170f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-b170f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANI6byoJCG49qYRjsTMfizYGmE4ztjaOs',
    appId: '1:538710833734:android:0bb30ee8948eeb92976847',
    messagingSenderId: '538710833734',
    projectId: 'iot-project-b170f',
    databaseURL: 'https://iot-project-b170f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-b170f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPTMeoUROeWJT60Vjw4Xi2PN_znecp_iE',
    appId: '1:538710833734:ios:b3063f3bf73f3989976847',
    messagingSenderId: '538710833734',
    projectId: 'iot-project-b170f',
    databaseURL: 'https://iot-project-b170f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-b170f.appspot.com',
    iosBundleId: 'com.example.guidedcariot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPTMeoUROeWJT60Vjw4Xi2PN_znecp_iE',
    appId: '1:538710833734:ios:b3063f3bf73f3989976847',
    messagingSenderId: '538710833734',
    projectId: 'iot-project-b170f',
    databaseURL: 'https://iot-project-b170f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-b170f.appspot.com',
    iosBundleId: 'com.example.guidedcariot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJfHtlzku7iAO27qoUq-tkLmBjAsQYg7M',
    appId: '1:538710833734:web:249b1503fd025b94976847',
    messagingSenderId: '538710833734',
    projectId: 'iot-project-b170f',
    authDomain: 'iot-project-b170f.firebaseapp.com',
    databaseURL: 'https://iot-project-b170f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-b170f.appspot.com',
  );
}
